# Generated by Django 2.2.4 on 2019-08-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_clearance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='dean',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to='form.ClearanceStatus'),
        ),
    ]
