# Generated by Django 2.2.4 on 2019-08-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20190823_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='form.ClearanceStatus'),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='chairman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to='form.ClearanceStatus'),
        ),
    ]
